# Test Validations

### Create asset bad request with empty data
POST http://localhost:3000/api/assets
Content-Type: application/json

{
  "id": "",
  "symbol": ""
}

### Create asset bad request with invalid data type
POST http://localhost:3000/api/assets
Content-Type: application/json

{
  "id": 1,
  "symbol": 1
}

### Create order bad request with invalid asset_id
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "1003",
  "price": 99.90
}

### Create order bad request status cannot be present in json
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "1001",
  "price": 99.91,
  "status": "closed"
}

### Create order bad request with empty data
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "",
  "price": 99.90
}

### Create order bad request with invalid data type
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": 0,
  "price": "99.90"
}

### Create order bad request with not positive price 
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "1001",
  "price": 0
}

### GET Test Hello
GET http://localhost:3000/test/hello
