services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      - db
  db:
    build: ./.docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
